### ISSUE TITLE
Getting up and running

### ISSUE THREAD

**Issue by Quintasan** [MaximumSquotting/raziel#1]
- [x] Install ~~Gentoo~~ any Linux distribution
- [x] Install [Ruby and Rails](https://gorails.com/setup/ubuntu/16.04) (use RVM and PostgreSQL)
- [ ] Learn [Ruby](http://rubykoans.com/)
- [ ] Learn Rails basics using [this](http://guides.rubyonrails.org/getting_started.html) or [this](https://www.railstutorial.org/book). Preferably both.

Note every single goddamn thing you don't get and ask me.

**Comment by bblazik** [comment]
Porobili my, porobili ale w sumie to nuda i do dupy daj nam normalne zadanie bedziem rozkminiac by doing na real case'ach xD
